import Head from "next/head";
import React, { FC, useEffect, useState } from "react";
import { getData } from "../api/agents";
import { useRouter } from "next/router";
import Image from "next/image";
import styled from "styled-components";
import { GetServerSideProps } from "next";

const Layout = styled.div`
  background-color: palegoldenrod;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const Container = styled.div`
  background-color: palevioletred;
  width: 500px;
  height: 600px;
  border-radius: 10px;
  padding: 10px;
`;

const Header = styled.h1`
  font-size: 24px;
  color: white;
  text-align: center;
`;
const Descp = styled.p`
  font-size: 14px;
  color: gray;
`;
const Img = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
`;
interface ICard {
  id: string;
}
const Card: FC<ICard> = () => {
  const router = useRouter();
  const { id } = router.query;
  console.log("RPUTE", router, "ID", id);

  const { status, data, error, isFetching } = getData(id as string);
  if (status === "loading" && !isFetching) {
    return (
      <Layout>
        <Container>
          <div>...</div>
        </Container>
      </Layout>
    );
  }
  if (status === "error") {
    router.back();
  }
  return (
    <div>
      <Head>
        <title>{data?.title}</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container>
          <Header>{data?.title}</Header>
          <Img>
            {data?.imgUrl && (
              <Image
                src={data?.imgUrl as string}
                width="300px"
                height="450px"
                className="image"
              />
            )}
          </Img>
        </Container>
      </Layout>
    </div>
  );
};

export default Card;
