import Head from "next/head";
import React, { ChangeEvent, KeyboardEvent, useState } from "react";
import styled from "styled-components";
import { useRouter } from "next/router";

const Layout = styled.div`
  background-color: blueviolet;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`;
const Container = styled.div`
  background-color: purple;
  width: 600px;
  height: 600px;
  border-radius: 10px;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
`;

const Title = styled.h1`
  color: white;
  margin-top: -20px;
  padding-bottom: 30px;
  font-size: 40px;
`;
const Input = styled.input`
  padding-left: 20px;
  width: 70%;
  height: 40px;
  border-radius: 10px;
  outline: none;
`;

const Main = () => {
  const router = useRouter();
  const [url, setUrl] = useState("");
  const onChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUrl(e.target.value);
  };
  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === "Enter") {
      router.push({
        pathname: "/card/[id]",
        query: { id: url },
      });
    }
  };
  return (
    <>
      <Head>
        <title>Movie DB scapper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container>
          <Title>Add Url</Title>
          <Input onChange={onChange} onKeyDown={handleKeyDown} />
        </Container>
      </Layout>
    </>
  );
};

export default Main;
